data:
  dataset: {name: mnist, samples: 70000, type: public}
  datasetLoadOption: full
  kfold: 1
  mapping:
    Digit Label:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
    Image:
      options: {Augmentation: false, Height: 28, Normalization: false, Resize: false,
        Scaling: 1, Width: 28, height_shift_range: 0, horizontal_flip: false, pretrained: None,
        rotation_range: 0, shear_range: 0, vertical_flip: false, width_shift_range: 0}
      port: InputPort0
      shape: ''
      type: Image
  numPorts: 1
  samples: {split: 1, test: 0, training: 56000, validation: 14000}
  shuffle: false
model:
  connections:
  - {source: Convolution2D_3, target: Convolution2D_4}
  - {source: Convolution2D_1, target: Convolution2D_2}
  - {source: Convolution2D_2, target: MaxPooling2D_1}
  - {source: Flatten_1, target: Dense_1}
  - {source: Dropout_1, target: Dense_2}
  - {source: Dropout_2, target: Dense_3}
  - {source: Dense_3, target: Output_1}
  - {source: Dense_2, target: Dropout_2}
  - {source: Dense_1, target: Dropout_1}
  - {source: MaxPooling2D_2, target: Flatten_1}
  - {source: Input_1, target: Convolution2D_1}
  - {source: MaxPooling2D_1, target: Convolution2D_3}
  - {source: Convolution2D_4, target: MaxPooling2D_2}
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 100
    y: 26
  - args: {}
    class: Flatten
    name: Flatten_1
    x: 374
    y: 39
  - args: {activation: sigmoid, output_dim: '1024'}
    class: Dense
    name: Dense_1
    x: 393
    y: 187
  - args: {p: '0.2'}
    class: Dropout
    name: Dropout_1
    x: 405
    y: 300
  - args: {activation: sigmoid, output_dim: '1024'}
    class: Dense
    name: Dense_2
    x: 676
    y: 78
  - args: {p: '0.2'}
    class: Dropout
    name: Dropout_2
    x: 690
    y: 220
  - args: {activation: softmax, output_dim: '10'}
    class: Dense
    name: Dense_3
    x: 700
    y: 373
  - args: {}
    class: Output
    name: Output_1
    x: 710
    y: 514
  - args: {activation: relu, nb_col: '3', nb_filter: '32', nb_row: '3'}
    class: Convolution2D
    name: Convolution2D_1
    x: 107
    y: 154
  - args: {activation: relu, nb_col: '3', nb_filter: '32', nb_row: '3'}
    class: Convolution2D
    name: Convolution2D_2
    x: 110
    y: 260
  - args: {activation: relu, nb_col: '3', nb_filter: '64', nb_row: '3'}
    class: Convolution2D
    name: Convolution2D_3
    x: 116
    y: 439
  - args: {}
    class: MaxPooling2D
    name: MaxPooling2D_1
    x: 112
    y: 344
  - args: {activation: relu, nb_col: '3', nb_filter: '64', nb_row: '3'}
    class: Convolution2D
    name: Convolution2D_4
    x: 115
    y: 531
  - args: {}
    class: MaxPooling2D
    name: MaxPooling2D_2
    x: 101
    y: 641
params:
  batch_size: 32
  loss_func: categorical_crossentropy
  num_epoch: 10
  optimizer: {name: Adadelta}
project: MNIST Handwritten Digits Classifier
